first/urls.py
from django.contrib import admin 
from django.urls import path , include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
   path('',include('sci.urls', namespace='sci')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sci/urls.py
from .views import ListViewPage  , first_view , DetailViewPage ,DetailApiView , ListApiView
from django.urls import path

urlpatterns = [
    path('',ListViewPage.as_view(), name = 'index'),
    path('sci/<slug>/',DetailViewPage.as_view() , name = "detail"),
    path('first/',first_view , name = 'first'),
    path('api/',ListApiView.as_view()),
    path('api/<slug>' , DetailApiView.as_view()),

]
app_name = 'sci'

account/models.py
from django.db import models

# Create your models here.

sci/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import post_save
import pandas as pd
import seaborn as sns
import numpy as np 
# Create your models here.
class DatasetManager(models.Manager):
    def mk_ready_dataset(self,slug, *args , **kwargs):
        # print("this is self", self)
        # print("this is request" , slug)
        # print("this is args" , args)
        # print("this is kwargs" , kwargs.keys())
        df = self.get(slug = slug)
        data = pd.read_csv(df.file)
        print(type(data))
        head_of_dataset = data.head()
        shape_of_dataset = data.shape
        info_of_dataset = self.change_to_dict(data.describe())
        dict_of_dataset = {
            'shape':shape_of_dataset,
            'describe':info_of_dataset,
            'head':head_of_dataset,
            'data_frame':data,
        }
        return dict_of_dataset
        
    def change_to_dict(self,DataFrame):
        dict_of_dataset = DataFrame.to_dict()
        return dict_of_dataset
class Dataset(models.Model):
    name = models.CharField(max_length=120)
    id = models.AutoField(primary_key=True)
    #size = models.CharField(max_length = 120)
    file = models.FileField(blank=True , null = True)
    slug = models.SlugField(max_length=120 , blank=True)
    objects = DatasetManager()
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "sci/{slug}".format(slug = self.slug)



#def data_file_reciever(sender , instance , *args, **kwargs):

account/views.py
from django.shortcuts import render

# Create your views here.

sci/views.py
from django.views.generic import ListView  ,DetailView
from django.shortcuts import render , HttpResponse , Http404
from django.http import JsonResponse
from .models import Dataset
import pandas as pd
import numpy as np
from plotly.offline import plot
import plotly.graph_objs as go
import plotly.express as ex
from .serializers import SciSerializer
from rest_framework import generics


class ListViewPage(ListView):
    model = Dataset
    template_name = 'list.html'
    def get_context_data(self, **kwargs):
        context = super(ListViewPage, self).get_context_data(**kwargs)
        context['Data'] = Dataset.objects.all()
        print(context) 
        return context
class DetailViewPage(DetailView):
    model = Dataset
    template_name = 'detail.html'
    def get_context_data(self , *args, **kwargs):
        dic_of_dataset = Dataset.objects.mk_ready_dataset(self.kwargs['slug'])
        fig = go.Figure()
        scatter = go.Scatter(x= [0 ,3 ,4 ,5],  y =[1 ,3 ,4 ,5]  , opacity = 0.9)
        # sec_scatter = ex.Scatter(x= [0 ,3 ,4 ,5],  y =[1 ,3 ,4 ,5]  , opacity = 0.9)
        fig.add_trace(scatter)
        plot_div = plot(fig , output_type= 'div')
        # print(dic_of_me)
        # request = self.request
        # print(self.kwargs['slug'])
        # print(self.kwargs)
        # print(type(dic_of_me['describe']))
        # dataset_id=request.session.get('dataset_id' , None)
        # first = Dataset.objects.get(slug = self.kwargs['slug'])
        context = super(DetailViewPage,self).get_context_data(*args, **kwargs)
        # Csv_file = context['object'].file
        # data_set = pd.read_csv(Csv_file).head(20)
        df = dic_of_dataset['data_frame']
        head_df=df.head().to_html(classes = 'mystyle')
        # dict_of_data = data_set.to_dict()
        # # keys_of_dict = dict_of_data.keys()
        # array_of_keys =  np.array(keys_of_dict)
        # print(type(array_of_keys))
        context={
            'head_df':head_df,
            'df' : df, 
            'dic_of_dataset':dic_of_dataset, 
            'plot_div' : plot_div ,        
        }
        
        return context

def first_view(request):
    print('this is my request',request)
    print("this is the slug:",DatasetModel.slug)
    return render(request , 'test.html', context = {})

class ListApiView(generics.ListAPIView):
    queryset = Dataset.objects.all()
    serializer_class = SciSerializer

class DetailApiView(generics.RetrieveAPIView):
    queryset = Dataset.objects.all()
    serializer_class = SciSerializer
        

sci/templates/detail.html
{%extends 'base/base.html'%}
{%block content%}
{% load static %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

<style>
  img.bg {
    /* Set rules to fill background */
    min-height: 100%;
    min-width: 1024px;
    
    /* Set up proportionate scaling */
    width: 100%;
    height: auto;
    
    /* Set up positioning */
    position: fixed;
    top: 0;
    left: 0;
  }
    
  </style>
<div class='container'>
    <P>THIS IS PARAGRAPH FIRST</P>
this is shape</br>
    {{shape}}
    that was shape
    {{dic_of_dataset.shape}}
    <div class="row"></div>
   {%for keys , values in dic_of_dataset.describe.items%}
   <div class="col-md-3">
     {{keys}}
     {%for k , v in values.items%}
     <div class="col-sm">
       {{k}}
       {{v}}
     </div>
     {%endfor%}
   </div>
   {%endfor%}
   </div>
</div>
<div class="container">
    {{head_df|safe}}
    this is div_plot
    {{plot_div|safe}}
 
 </div>

 <article class="container">
  <style type="text/css">
    .mystyle{
      text-align: center;
    }
    body {
    font-family: Georgia, Times, serif;}
    h1, h2 {
    font-family: Arial, Verdana, sans-serif;}
    .credits {
    font-family: "Courier New", Courier,
    monospace;}
    #col_of_fuck{
      /* background-color:#2D06BE; */
      color:#2D06BE;
      /* padding:10px; */
      column-rule-style: dotted;
      column-count:3;

    }


    </style>


 </article>

 <div class="container">
   this is dataset : {{data_set}}
  {{keys_of_dict}}
  <H1>this is new pdf</H1>
  <!-- {{dict_of_data}} -->
  this is arrayes of keys
  <div class="row" id = 'row_of_fuck'>
  {% for i in keys_of_dict %}
    <div class="col" id = 'col_of_fuck'>
      {{i}}
    </div>
 
  {%endfor%}
</div>

  {{array_of_keys}}
 </div>
 <canvas id="bar-chart"> </canvas>
 <script>
    
        new Chart(document.getElementById("bar-chart"), {
        type: 'bar',
        data: {
          labels: ["Africa", "Asia", "Europe", "Latin America", "North America"],
          datasets: [
            {
              label: "My first Data Set",
              backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
              data: [2478,5267,734,784,433]
            }
          ]
        },
        options: {
          legend: { display: false },
          title: {
            display: true,
            text: 'Predicted world population (millions) in 2050'
          }
        }
    });
     </script>

    <article class="container" id="first_id">

      <form action="{% url 'sci:first' %}" class="AjaxForm"> {% csrf_token %}
        <p>this is form</p>
        <input type="hidden" value="{{DataSetModel_id }}">
        <button type="submit" class="btn btn-link btn-sm" style="padding: 0px;cursor:pointer;">from</button>
      </form>

     

    </article>
      <canvas id = 'SecondChart'>

      </canvas>

      <script>
    console.log('this is the first')
    var ctx = document.getElementById("SecondChart")    
    var chart = new Chart(ctx , {
          type : 'scatter',
          data: { 
           labels : ['Ahmad', 'Mohammad' , 'Omid' , 'Atefeh' , 'Shekofeh' , "Fahime"],
            datasets : [{ 
              label : 'ScaterDataset',
              // backgroundColor = ["#3e95cd"],
              data: [1,2,3,4,5,65]
            }]
          },
          options : {
            scales: {
            xAxes: [{
                type: 'linear',
                position: 'bottom'
            }]
        }
          }
        });

      </script>

<div style="width:45%; float: left; margin-left: 25px"> 
  <canvas id="ThirdChart"></canvas>
</div>

      
      <script>
console.log("this is the Second")
var ctx = document.getElementById("ThirdChart");
var scatterChart = new Chart(ctx, {
    type: 'scatter',
    data: {
        datasets: [{
            label: 'Scatter Dataset',
            pointHoverBorderColor: 'rgba(100, 0, 0, 0.1)',
            data: [{
                x: -10,
                y: 0
            }, {
                x: 0,
                y: 10
            }, {
                x: 10,
                y: 5
            }]
        }]
    },
    options: {
        scales: {
            xAxes: [{
                type: 'linear',
                position: 'bottom'
            }]
        }
    }
});
      </script>


 

{%endblock content%}

sci/templates/list.html
{% extends 'base/base.html'%}
{% load static %}
{% block content %}
{% load static %}
<style>
  .card {
    /* Add shadows to create the "card" effect */
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
  }
  
  /* On mouse-over, add a deeper shadow */
  .card:hover {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
  }
  
  /* Add some padding inside the card container */
  .container {
    padding: 2px 16px;
  }
  img.bg {
  /* Set rules to fill background */
  min-height: 100%;
  min-width: 1024px;
	
  /* Set up proportionate scaling */
  width: 100%;
  height: auto;
	
  /* Set up positioning */
  position: fixed;
  top: 0;
  left: 0;
}
  
</style>

<article>
<img src="{% static 'isaac-smith-6EnTPvPPL6I-unsplash.jpg' %}" class = 'bg' alt="this is image">
</article>

<div class = 'container'>
  this is contex
  {{context}}

        <div class= 'row'>
          {%for file in object_list%}
          <div class='col-md-3'>
            <div class = 'card'>
              <a href="{{file.get_absolute_url }}">
              <img src="{% static 'document.jpg' %}" alt="My image" style="width:100%">
              </a>
              {{file.name}}
            </div>
          </div>
       
        {%endfor%}
      </div>
</div>





{%endblock content%}

sci/templates/test.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <canvas id="myChart"> </canvas>

    <style>

.col-sm-4:hover::after { 
   background-color: #ffa;
   content: '\00a0';  
   height: 10000px;    
   left: 0;
   position: absolute;  
   top: -5000px;
   width: 100%;
   z-index: -1;  
   text-align: center;      
}
.col-sm-4{
  text-align: center;
}

    </style>
    <div class='container'>
      <div class="row">
        <div class="col-sm-4">.col-sm-4</div>
        <div class="col-sm-4">.col-sm-4</div>
        <div class="col-sm-4">.col-sm-4</div>
      </div>
      </div>
    
</body>
</html>

sci/templates/test2.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>



</body>
</html>

templates/base/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% load static %}
    <title>Hello, world!</title>
  </head>
  <body>
    
    <h1>Hello, world!</h1>
     {%block content%}
     {%endblock%}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>